
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS' | 'HEAD';

export interface ExampleResponse {
  statusCode: number;
  body: string; // JSON string or other text format
  description?: string; // Optional description for this specific response
}

export interface ApiEndpointDefinition {
  id: string; // Unique ID generated by the application, not by the parser initially
  method: HttpMethod;
  path: string;
  description?: string;
  defaultResponse: string; // Stores the primary/successful response body for simple UI and backward compatibility
  exampleResponses: ExampleResponse[]; // Stores all parsed responses with their status codes
}

export interface MockedEndpoint extends ApiEndpointDefinition {
  mockResponse: string; // Editable mock response, initially same as defaultResponse. UI currently edits this.
  // The mock server currently uses this mockResponse.
}

export interface ConfluenceDocument {
  id: string; // Unique ID for this parsed document, typically the confluenceLink
  title: string;
  confluenceLink: string;
  endpoints: MockedEndpoint[];
  isMockActive: boolean; // Tracks if the mock server for this document is active
}
